version: 2.1

orbs:
  vst: vst/vst-native-orb@9.1.0

.current_filters: &current_filters
  branches:
    only:
      - main
      - next
      - /^pr-ci\/.+/

.package-name: &package-name openh264

jobs:
  linux-build:
    executor: vst/linux
    steps:
      - vst/setup
      - vst/setup_linux
      - vst/install_conan_and_configure
      - run: |
          channel=${CIRCLE_BRANCH//[_+=.,\/]/-}
          conan create -pr emscripten -s "build_type=Release" -s "os.threads=True" conan "vernierst+vst-libs/${channel}"
      - run: |
          channel=${CIRCLE_BRANCH//[_+=.,\/]/-}
          conan create -pr emscripten -s "build_type=Debug" -s "os.threads=True" conan "vernierst+vst-libs/${channel}"
      - vst/upload:
          package_name: *package-name

workflows:
  version: 2
  build:
    jobs:
      - linux-build:
          context: orb-publishing
          filters:
            <<: *current_filters
